query latest {
    dagger {
        engine(version: "0.8.5") {
            cli(operatingSystem: "darwin", arch: "amd64") {
                export(path: "bin/dagger-0.8.5")
            }

            source {
                export(path: "dagger-0.8.5/")
            }
        }
    }
}
